log:
  level: warn
  file: ""

include: []

plugins:
  - tag: no_aaaa_domains
    type: domain_set
    args:
      files:
        - "/etc/mosdns/no_aaaa_domains.txt"

  - tag: remote_dns
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "tls://8.8.8.8"
          enable_pipeline: true
        - addr: "tls://8.8.4.4"
          enable_pipeline: true
        - addr: "tls://1.1.1.1"
          enable_pipeline: true
        - addr: "tls://1.0.0.1"
          enable_pipeline: true

  - tag: cache
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 86400

  - tag: main
    type: sequence
    args:
      - matches:
          - qtype 28
          - qname $no_aaaa_domains
        exec: reject 0
      - exec: $cache
      - matches:
          - has_resp
        exec: accept
      - exec: $remote_dns

  - type: udp_server
    args:
      entry: main
      listen: 0.0.0.0:5355

  - type: tcp_server
    args:
      entry: main
      listen: 0.0.0.0:5355
